### ISSUE TITLE
BUG for loss function in pytorch 0.4 python3.5

### ISSUE THREAD

**Issue by oujieww** [meetshah1995/pytorch-semseg#106]
i use this : pytorch 0.4 python3.5
if size_average:
loss /= mask.data.sum().float()
return loss

for this problem:

File "./new_train.py", line 91, in train
loss = loss_fn(input=outputs, target=labels)
File "/mnt/disk2/oujie/DFN/pytorch-semseg-master/ptsemseg/loss.py", line 31, in cross_entropy2d
loss /= mask.data.sum().
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #3 'other'

I do not know if this change is okay?  but not by this change .float()  it starts training

**Comment by meetshah1995** [comment]
The fix is correct for torch-0.4.
