### ISSUE TITLE
Weird path in cityscapes loader

### ISSUE THREAD

**Issue by thedch** [meetshah1995/pytorch-semseg#111]
What is this line doing?

https://github.com/meetshah1995/pytorch-semseg/blob/master/ptsemseg/loader/cityscapes_loader.py#L69

```
self.annotations_base = os.path.join(self.root, 'gtFine_trainvaltest', 'gtFine', self.split)
```

I modified it to be:

```
self.annotations_base = os.path.join(self.root, 'gtFine', self.split)
```

but I run into more errors later in the script. Do I have the data set up wrong?

**Comment by SunnerLi** [comment]
Hi @thedch ,
maybe we should clarify the function of `os.path.join`.
This is the function to form the path with automatic.
For example, if the `self.root` is `/home/user',
You can assign the path directly: 
```python
absolute_path = self.root + '/gtFine_trainvaltest'
print(absolute_path)
# Output:  /home/user/gtFine_trainvaltest
```
On the other hand, you can let the package to do:
```
absolute_path = os.path.join(self.root + 'gtFine_trainvaltest')
print(absolute_path)
# Output:  /home/user/gtFine_trainvaltest
```

You should be aware the path of the CityScape dataset.
The normal folder name is `gtFine_trainvaltest`.
However, you should change the name if the name of the ground truth folder is not the same.

**Comment by thedch** [comment]
Ahhh, I did not realize that the dataset normally comes downloaded with the folder name `gtFine_trainvaltest`, -- that bit confused me. Thanks!
