### ISSUE TITLE
Error when running PSPNet with PascalVOC

### ISSUE THREAD

**Issue by flriancu** [meetshah1995/pytorch-semseg#115]
Hello,

When I run `python train.py --arch pspnet --dataset pascal --n_epoch 500 --batch_size 8`
I get the following error.
Tested with PyTorch 0.4.1 on Linux.

```
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    train(args)
  File "train.py", line 92, in train
    loss.backward()
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

I suspect it might be from the `cross_entropy2d` in `ptsemseg/loss.py`, but I am not sure. Please let me know if you need more details.

**Comment by adam9500370** [comment]
Hi, @flriancu .
You can check #96 .

**Comment by flriancu** [comment]
@adam9500370 Thanks, solved. Any idea if the `align_corners` being [turned off by default](https://pytorch.org/docs/stable/nn.html?highlight=align_corners#torch.nn.Upsample) in 0.4 has any influence for the results ([see comment in #96](https://github.com/meetshah1995/pytorch-semseg/issues/96#issuecomment-398960544))?

**Comment by adam9500370** [comment]
I think you still need to set `align_corners=True`. ([see comment in #81](https://github.com/meetshah1995/pytorch-semseg/pull/81#issuecomment-412283369))
