### ISSUE TITLE
No such file or directory: '/home/gpu_users/meetshah/segdata/pascal/benchmark_RELEASE/dataset/train.txt'

### ISSUE THREAD

**Issue by liwei46** [meetshah1995/pytorch-semseg#138]
Hi all,

I try to run the train.py,  with --config configs/fcn8s_pascal.yml after I change the path for VOC dataset
but I encounter the following error.  
FileNotFoundError: [Errno 2] No such file or directory: '/home/gpu_users/meetshah/segdata/pascal/benchmark_RELEASE/dataset/train.txt'

Anyone know how to genrate the train,txt. 

Thanks a lot!

**Comment by liwei46** [comment]
actually this is just need to download the sdb dataset.

**Comment by 3bobo** [comment]
what's the  sbd datasets? I'm failed to find it

**Comment by johnathanchiu** [comment]
What is the link for the dataset?

**Comment by mlx123** [comment]
Can you tell me where I can get the  sdb dataset,thank you.

**Comment by mlx123** [comment]
I download the SBD from http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz
and the things inside it like below picture
![default](https://user-images.githubusercontent.com/28173246/50225484-a146be80-03db-11e9-917e-fdc82b846187.png)
![default](https://user-images.githubusercontent.com/28173246/50225495-adcb1700-03db-11e9-9baa-febb3d593f2a.png)


it is different from the code of   ptsemseg/loader/pascal_voc_loader.py
![default](https://user-images.githubusercontent.com/28173246/50225399-5f1d7d00-03db-11e9-99a7-4c3b95f25c98.png)

I cannot find the "sbd" and the "SegmentationClass/pre_encoded"

**Comment by farnaznouraei** [comment]
@liwei46 Hi did you manage to resolve this issue? I am getting a FileNotFound error while I have the train.txt file in the path I have specified
