### ISSUE TITLE
no config.json file

### ISSUE THREAD

**Issue by renlikun1988** [meetshah1995/pytorch-semseg#153]
Hello, when I run train.py with pascal dataset, filenofounderror 'no such file or directory config.json' is shown. The error is located in get_data_path function in pascal_voc_loader.py. So how to fix it? Thx!

**Comment by LevineYang** [comment]
sorry, but how did you solve it and close the issue? I also encounter this problem...

**Comment by renlikun1988** [comment]
that function returns the path to voc augmentation dir, so I provide the path to where  that function is called.

**Comment by LevineYang** [comment]
okay. I see, thank you!

**Comment by johnathanchiu** [comment]
Are we supposed to create out own config file or does the code already come with one? If so, where is the config file located?

**Comment by devraj89** [comment]
Hi @renlikun1988 @LevineYang can someone provide a demo config file? I am stuck and unable to run the code for quite some time due to this issue.

**Comment by renlikun1988** [comment]
I cannot find the config file through the repo.  I didn't use the config file and instead provide the path of voc augmentation dataset to where the function get_data_path is call. @johnathanchiu @devraj89

**Comment by zhenxingsh** [comment]
> Hello, when I run train.py with pascal dataset, filenofounderror 'no such file or directory config.json' is shown. The error is located in get_data_path function in pascal_voc_loader.py. So how to fix it? Thx!

hi, can you give me a demo about config.json.?
