### ISSUE TITLE
Pretrained models?

### ISSUE THREAD

**Issue by lolz0r** [meetshah1995/pytorch-semseg#18]
Hi,
It would be super if pretrained models were provided! 

Thank you!
Michael

**Comment by meetshah1995** [comment]
Sure, I'm planning to update the PyTorch version and a few other things. I'll retrain the models and share the weights after that. Might take sometime.

**Comment by fanser** [comment]
Hello, where can I download your trained model? Thanks!

**Comment by Inaaa** [comment]
I have the same questions. where can I find trained models of cityscapes?
