### ISSUE TITLE
Multiple GPU mode

### ISSUE THREAD

**Issue by july11** [meetshah1995/pytorch-semseg#22]
Does the code support multi-gpu?

**Comment by zhxt0** [comment]
It seems that does not support multi-gpu, but you can add by yourself
http://pytorch.org/docs/master/nn.html?highlight=datapar#torch.nn.DataParallel
```
net = torch.nn.DataParallel(model, device_ids=[0, 1, 2])
output = net(input_var)
```

**Comment by meetshah1995** [comment]
I only had 1 GPU when I started pytorch-semseg, as @zhxt0 pointed out, you can simply use two ( or more ) by `nn.DataParallel`.

I'll make the change in the train and validate scripts for support Multi-GPU ( if present ).
