### ISSUE TITLE
iisue in testing script

### ISSUE THREAD

**Issue by anssandeep** [meetshah1995/pytorch-semseg#25]
I have trained segnet on camvid dataset and while testing I came across the following issue 

python test.py --model_path segnet_camvid_1_8.pkl --dataset camvid --img_path /home/ubuntu/workspace/SegNet-Tutorial/CamVid/val/0016E5_08105.png --out_path out.png
Read Input Image from : /home/ubuntu/workspace/SegNet-Tutorial/CamVid/val/0016E5_08105.png
Traceback (most recent call last):
  File "test.py", line 67, in <module>
    test(args)
  File "test.py", line 50, in test
    pred = np.squeeze(outputs.data.max(1)[1].cpu().numpy(), axis=1)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 1198, in squeeze
    return squeeze(axis=axis)
ValueError: cannot select an axis to squeeze out which has size not equal to one

Could someone please provide workaround for the issue. Thank you.

**Comment by zhxt0** [comment]
You can ref Issue #19
