### ISSUE TITLE
About ade20k_loader

### ISSUE THREAD

**Issue by Eniac-Xie** [meetshah1995/pytorch-semseg#27]
Hi, thank you for your code!

I want to use the ptsemseg/loader/ade20k_loader.py, in the function:
```
    def encode_segmap(self, mask):
        # Refer : http://groups.csail.mit.edu/vision/datasets/ADE20K/code/loadAde20K.m
        mask = mask.astype(int)
        label_mask = np.zeros((mask.shape[0], mask.shape[1]))
        label_mask = ( mask[:,:,0] / 10.0 ) * 256 + mask[:,:,1]
        return np.array(label_mask, dtype=np.uint8)
```
the label_mask is with elements that larger than 256, so why do you use dtype=np.uint8 (which means `mask[:,:,0] / 10.0 ) * 256` will be discarded).

**Comment by meetshah1995** [comment]
`n_classes` is only 150, so I think the max value label_mask can take is 150 (inside uint8 range).

Can you point to a specific instance from the ADE20K dataset where this doesn't work?

**Comment by jxlijunhao** [comment]
@meetshah1995  @Eniac-Xie   I have same problem and confused by this encode utils,  for exampe, the images in the trainning set        **a/abbey/ADE_train_00000971.jpg**

using above functions and  np.unique(mask), the results will gave:
[  0  39  56 101 116 255]

**Comment by fido20160817** [comment]
what does "label_mask = ( mask[:,:,0] / 10.0 ) * 256 + mask[:,:,1]" mean? the dimension of the mask is 2 so an error happens here. But I don't what this code means, so I can not change it.  @meetps

**Comment by fido20160817** [comment]
where to download ...seg.png?
