### ISSUE TITLE
possible missing funcction in camvid_loader.py

### ISSUE THREAD

**Issue by donghaozhang** [meetshah1995/pytorch-semseg#30]
Dear, 
Thank you so much for the  wonderful code. 
Is that the following functions required by camvid_loader.py?
Kind Regards,
Donghao

 def get_camvid_labels(self):
        return np.asarray([[128, 128, 128], [128, 0, 0], [192, 192, 128], [255, 69, 0], [128, 64, 128], [60, 40, 222], [128, 128, 0], [192, 128, 128], [64, 64, 128], [64, 0, 128], [64, 64, 0], [0, 128, 192], [0, 0, 0]])

    def encode_segmap(self, mask):
        mask = mask.astype(int)
        label_mask = np.zeros((mask.shape[0], mask.shape[1]), dtype=np.int16)
        for i, label in enumerate(self.get_camvid_labels()):
            label_mask[np.where(np.all(mask == label, axis=-1))[:2]] = i
        label_mask = label_mask.astype(int)
        return label_mask

**Comment by meetshah1995** [comment]
Nope, not needed, CamVid annotations are labelID based not RBG based.
