### ISSUE TITLE
UserWarning: self and mask not broadcastable, but have the same number of elements

### ISSUE THREAD

**Issue by karlTUM** [meetshah1995/pytorch-semseg#33]
Hi,
I am using pytorch 0.20 to train my network. Due to the broadcasting change in this version, it usually comes out warning:

```
~/anaconda3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py:468: UserWarning: self and mask not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_select(mask)
~/anaconda3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py:416: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor1.masked_scatter_(mask, tensor2)
```

**Comment by donghaozhang** [comment]
def cross_entropy2d(input, target, weight=None, size_average=True):
    n, c, h, w = input.size()
    log_p = F.log_softmax(input)
    log_p = log_p.transpose(1, 2).transpose(2, 3).contiguous().view(-1, c)
    log_p = log_p[target.view(n * h * w, 1).repeat(1, c) >= 0]
    log_p = log_p.view(-1, c)
    mask = target >= 0

    target = target[mask]
    loss = F.nll_loss(log_p, target, weight=weight, size_average=False)
    if size_average:
        loss /= mask.data.sum()
    return loss

**Comment by MatthewKleinsmith** [comment]
@donghaozhang 

The new function you provided removes the mentioned errors, but new ones come if one tries to do anything with the input, target, or loss afterward.

#### For example:

After an attempt to print the input:

> RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensorCopy.c:65

After setting size_average=True:

> RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generated/../THCReduceAll.cuh:334

**Comment by meetshah1995** [comment]
3fd5faf96f4a5c83a2e56f121b508fc7fd53cbae Fixes this.
