### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'unsqueeze'

### ISSUE THREAD

**Issue by 4F2E4A2E** [meetshah1995/pytorch-semseg#39]
I am having big time troubles running this A.I. with CUDA 7.5 and cudnn 6 on Ubuntu 16.04 with python 2.7:
---
python train.py --arch segnet --batch_size 1 --img_rows 469 --img_cols 469 --dataset pascal
True: `print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(0)))`
6021: `print(torch.backends.cudnn.version())`
Cuda available.: `torch.cuda.is_available()`
```
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    train(args)
  File "train.py", line 41, in train
    test_image = Variable(test_image.unsqueeze(0).cuda(0))
AttributeError: 'numpy.ndarray' object has no attribute 'unsqueeze'
```

Any help would be much apreciated.

**Comment by 4F2E4A2E** [comment]
I can confirm that this error only appears if  [is_transform is set to False](https://github.com/meetshah1995/pytorch-semseg/blob/master/train.py#L24)
If set to true, i got this error:
```
(pytorch27) learner@learner:meetshah1995/pytorch-semseg$ python train2.py --arch segnet --batch_size 1 --dataset pascal
Traceback (most recent call last):
  File "train2.py", line 105, in <module>
    train(args)
  File "train2.py", line 61, in train
    loss = cross_entropy2d(outputs, labels)
  File "meetshah1995/pytorch-semseg/ptsemseg/loss.py", line 11, in cross_entropy2d
    log_p = log_p[target.view(n, h, w, 1).repeat(1, h, w, c) >= 0]
  File "/home/learner/.conda/envs/pytorch27/lib/python2.7/site-packages/torch/autograd/variable.py", line 471, in view
    return View(*sizes)(self)
  File "/home/learner/.conda/envs/pytorch27/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 98, in forward
    result = i.view(*self.sizes)
RuntimeError: size '[1 x 256 x 256 x 1]' is invalid for input of with 196608 elements at /b/wheel/pytorch-src/torch/lib/TH/THStorage.c:59
```

I am just trying to get it running with the VOC2012 dataset. All dataset files are double checked.
Is there a way to get it running?

I also had to adapt the dependencies (requirements.txt) to:
```
matplotlib==2.0.0
numpy==1.13.1
scipy==0.19.0
torch
torchvision
tqdm
visdom
certifi
```

**Comment by meetshah1995** [comment]
No issue in present master.
