### ISSUE TITLE
Regarding segnet

### ISSUE THREAD

**Issue by sriharsha0806** [meetshah1995/pytorch-semseg#44]
Hi,
          Regarding segnet upsasmpling segnetup3(), segnetup2(). shouldn't the code be 

class segnetUp2(nn.Module):
    def __init__(self, in_size, out_size):
        super(segnetUp2, self).__init__()
        self.unpool = nn.MaxUnpool2d(2, 2)
        self.conv1 = conv2DBatchNormRelu(in_size, in_size, 3, 1, 1)
        self.conv2 = conv2DBatchNormRelu(in_size, out_size, 3, 1, 1)

    def forward(self, inputs, indices, output_shape):
        outputs = self.unpool(input=inputs, indices=indices, output_size=output_shape)
        outputs = self.conv1(outputs)
        outputs = self.conv2(outputs)
        return outputs

class segnetUp3(nn.Module):
    def __init__(self, in_size, out_size):
        super(segnetUp3, self).__init__()
        self.unpool = nn.MaxUnpool2d(2, 2)
        self.conv1 = conv2DBatchNormRelu(in_size, in_size, 3, 1, 1)
        self.conv2 = conv2DBatchNormRelu(int_size, in_size, 3, 1, 1)
        self.conv3 = conv2DBatchNormRelu(in_size, out_size, 3, 1, 1)

  Because the Decoder Architecture according to the program is 
Deconv3-512X3->Deconv3-256X3--->Deconv3-128X3--->Deconv3-64X2--->Deconv3-21x2

But the actual architecture is 
Deconv3-512X3->Deconv3-512X3--->Deconv3-256X3--->Deconv3-128X2--->Deconv3-64x2

**Comment by meetshah1995** [comment]
Yup, thanks!

1b7d852..792d4c1 fixes it.
