### ISSUE TITLE
 vgg16 = models.vgg16(pretrained=True) TypeError: vgg16() takes no arguments (1 given)

### ISSUE THREAD

**Issue by ywangeq** [meetshah1995/pytorch-semseg#45]
Anyone can help me:
vgg16 = models.vgg16(pretrained=True)
TypeError: vgg16() takes no arguments (1 given)

**Comment by littlebelly** [comment]
pretrained vgg model is a new function, update your torchvision version and it will work

**Comment by meetshah1995** [comment]
Update torchvision
