### ISSUE TITLE
Feature scaling in Linknet

### ISSUE THREAD

**Issue by hhsecond** [meetshah1995/pytorch-semseg#48]
Hi,
Thanks for your work first of all. I was just wondering have you got any speed gain because of ``feature_scale `` you have used in linknet which reduces the filter size specified in the actual linknet paper. If not, could you explain why did you use ``feature_scale``

**Comment by hhsecond** [comment]
I feel terrible that I did not check the README before raising an issue. I got it now and thanks again

**Comment by d-li14** [comment]
@hhsecond Sorry, after checking the README, I'm still cofused about the `feature_scale` trick different from the original LinkNet, could you please give an explanation?
