### ISSUE TITLE
Is the model linknet the same with pspnet?

### ISSUE THREAD

**Issue by guanfuchen** [meetshah1995/pytorch-semseg#49]
I am wondering if it is a mistake that the model linknet is the same with pspnet.

**Comment by meetshah1995** [comment]
Yes it's a mistake. PSPnet is still WIP (see issue #29). I should probably remove the pspnet file for the time being. 

PS - It'd be great if you could send in a PR for PSPnet.

**Comment by guanfuchen** [comment]
I find other repo release some code about pspnet like[pspnet-pytorch](https://github.com/Lextal/pspnet-pytorch), but I am not trying these code training on real dataset. There is another problem about linknet, it is still on the progress? Some mistake [nn. deconv2DBatchNormRelu](https://github.com/meetshah1995/pytorch-semseg/blob/master/ptsemseg/models/utils.py#L223), and it can also not be trained

It is a good work for helping understand the semantic segment, and I will be happy if I can be some extra work.

**Comment by meetshah1995** [comment]
LinkNet works, you may want to checkout the `resnet-encoders` branch for a linknet with pre-trained resnet support. 

Regarding making a workable PSPNet, shall we continue the discussion on #29 ?
