### ISSUE TITLE
Cityscape data loader is not implemented - WIP

### ISSUE THREAD

**Issue by ibadami** [meetshah1995/pytorch-semseg#5]
In your wiki, it states that cityscape dataset loader is implemented but it is not in the repo :)
Thank you for the rest of the code though :+1:

**Comment by meetshah1995** [comment]
Ah, yes. Since I've ported this repo from an internal private torch repo, I thought that I already had ported the cityscapes loader. 

Will do that over the weekend.

**Comment by amiltonwong** [comment]
Hi, @meetshah1995 ,

Have you released the cityscapes loader?

Thanks!

**Comment by balloch** [comment]
Pinging this. Cityscapes loader?

**Comment by acgtyrant** [comment]
The longest weekend in history.

**Comment by catta202000** [comment]
Any update on this?

**Comment by meetshah1995** [comment]
@acgtyrant - Finding a job while doing your thesis takes time no? :)

I've been busy with my thesis, I'm not planning to write a loader for cityscapes, feel free to send in a PR.

The fastest way IMO, to do it would be to simply port the one [here](https://github.com/fvisin/dataset_loaders/blob/master/dataset_loaders/images/cityscapes.py) to the format pytorch-semseg uses.

**Comment by acgtyrant** [comment]
I wrote the loader for cityscapes myself already, but my company may does not agree I open its source.

I will advice the loader dependence on [cityscapesScripts](https://github.com/mcordts/cityscapesScripts), generate the new trainLabel image via `cityscapesscripts.preparation.json2labelImg.json2labelImg`.

By the way, the official vision is [planning extending the transforms](https://github.com/pytorch/vision/issues/230), so following this new proposal is better, as just adding the new attribute `transforms` to the `Dataset` class.

**Comment by achaiah** [comment]
In case you guys haven't found it yet, [this project](https://github.com/ZijunDeng/pytorch-semantic-segmentation) has a working cityscapes implementation (as well as VOC).

**Comment by meetshah1995** [comment]
Added here too.
