### ISSUE TITLE
Error in Visdom?

### ISSUE THREAD

**Issue by d-li14** [meetshah1995/pytorch-semseg#64]
When I set --visdom True, I got this error:
```shell
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    train(args)
  File "train.py", line 48, in train
    legend=['Loss']))
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 206, in result
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 769, in line
    update=update, name=name)
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 206, in result
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 635, in scatter
    assert Y.ndim == 1, 'Y should be one-dimensional'
AssertionError: Y should be one-dimensional
```
Could anyone explain how to fix that?

**Comment by zhoufengbuaa** [comment]
@d-li14 I got the same error. Did you solve it?

**Comment by d-li14** [comment]
Finally, I implemented the plotting with Visdom by myself.

**Comment by lxtGH** [comment]
@zhoufengbuaa just keep the Y and X in the same dimension(one-dimension), then the problem can be solved

**Comment by zhoufengbuaa** [comment]
@lxtGH How to keep? Could u show more detail how to change the code?

**Comment by lxtGH** [comment]
@zhoufengbuaa `loss_window = vis.line(X=torch.zeros((1)).cpu(),
                               Y=torch.zeros((1)).cpu(),
                               opts=dict(xlabel='minibatches',
                                         ylabel='Loss',
                                         title='Training Loss',
                                         legend=['Loss']))`

**Comment by zhoufengbuaa** [comment]
@lxtGH Thank you very much, I already discard the code about visdom and use tensorboard to show the training process instead.
