### ISSUE TITLE
Why using batch_size >1 it sgives an error 

### ISSUE THREAD

**Issue by sounakdey** [meetshah1995/pytorch-semseg#76]
Why using batch_size >1 it sgives an error : RuntimeError: NCCL Error 1: unhandled cuda error. I have checked at its not the issue with installation.

**Comment by sounakdey** [comment]
ahh got it the problem was with data parallel. Solved

**Comment by dreamegg** [comment]
How did U fix. I wonder "got it the problem was with data parallel"

> ahh got it the problem was with data parallel. Solved
