### ISSUE TITLE
How to finetune?

### ISSUE THREAD

**Issue by johnsrude** [meetshah1995/pytorch-semseg#78]
When I run `python train.py --arch linknet --dataset data_file --img_rows 512 --img_cols --n_epoch 200 --batch_size 10` twice in a row, the training starts again from scratch.

How do I finetune a dataset?  I need to run multiple times and adjust the  hyperparameters as the training progresses.

**Comment by keishatsai** [comment]
Hi,
Could you share how you do the finetune? Thank you.
