### ISSUE TITLE
Doubt in the parameters

### ISSUE THREAD

**Issue by bruno-krinski** [meetshah1995/pytorch-semseg#79]
Hi, I didn't understood the meaning of some parameters. If some one could help me, I'll be very grateful.

First, in training, what does the feature_scale parameter? 

Another doubt, also in training, the img_rows and img_cols are to make resizing in the input images or this comes from the size of the images in the dataset?

The last one is dcrf in test step, what is this DenseCRF based post-processing? 

Thanks.

**Comment by meetshah1995** [comment]
`feature_scale` parameter is depreciated and no longer in use. I will update the README with updated parameters.

**Comment by GutlapalliNikhil** [comment]
Hi @bruno-krinski , can I know what is that dcrf means?
thanks
