### ISSUE TITLE
The cross_entropy2d function in loss.py may have a error

### ISSUE THREAD

**Issue by BUPTAlanMa** [meetshah1995/pytorch-semseg#93]
The code is great!
When I run Unet using PASCAL VOC dataset.(Pytorch 0.4, python 2.7) There report a error. I debug and find It occure in the Code in **cross_entropy2d** function in **loss.py**
```
    if size_average:
        loss /= mask.data.sum()
    return loss
```
In my envir, it does not support the Tensor type Var directly devide. I repair like this
```
    if size_average:
        loss /= mask.data.sum().item()
    return loss
``` 
and It run correctly.

**Comment by oujieww** [comment]
i use this : 
    if size_average:
        loss /= mask.data.sum().float()
    return loss

for this problem:

  File "./new_train.py", line 91, in train
    loss = loss_fn(input=outputs, target=labels)
  File "/mnt/disk2/oujie/DFN/pytorch-semseg-master/ptsemseg/loss.py", line 31, in cross_entropy2d
    loss /= mask.data.sum().long()
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #3 'other'
