### ISSUE TITLE
inplace operation

### ISSUE THREAD

**Issue by zyfsa** [meetshah1995/pytorch-semseg#96]
i run the pspnet in pytorch0.2.0, but I met the error
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation.
thanks

**Comment by adam9500370** [comment]
Hi, @zyfsa .
Replace this line
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/models/pspnet.py#L84
with `self.dropout = nn.Dropout2d(p=0.1, inplace=False)` or just remove the inplace flag.
(Ref: https://github.com/pytorch/pytorch/issues/727)

**Comment by zyfsa** [comment]
hi, @adam9500370  I met a problem, when I run the linknet, why the GPU Memory is so small. I only use 487MiB,thank you for my issue

**Comment by adam9500370** [comment]
For the first problem, I think you can check whether the shape of `gt` and `pred` is consistent or not. They should be of the same shape.
For the second problem, can you share the exact command that you ran?

**Comment by zyfsa** [comment]
thank your reply.for the second problm,my comman is:
CUDA_VISIBLE_DEVICES=1 python train.py --arch 'linknet' --dataset 'ustc'
                --img_rows 384 --img_cols 512
                --n_epoch 20 --batch_size 32
                --l_rate 0.001 --feature_scale 1

for the first problem, I met many problems when I run the code with torch 0.2.0, please the version is important for this code? do you have a taste?

**Comment by adam9500370** [comment]
Some of the API (e.g, F.log_softmax, torch.arange) in 0.3.0 are slightly different from those in 0.2.0.
I suppose you can still modify some codes and make it run in pytorch 0.2.0, even though in my experience, pytorch 0.2.0 is pretty slow compared to 0.3.0.
Therefore, I would suggest using 0.3.0 to avoid API inconsistency and to have better performance.

**Comment by zyfsa** [comment]
thank you

**Comment by HPL123** [comment]
@adam9500370  @zyfsa ，Hi，did you have test the model？ I have test the model but the result is very bad. How about yours?
